path:
  stores: store.csv             # CSV file containing store information
  train: train.csv              # CSV file containing training data
  predictions: predictions.csv  # CSV file where predictions will be saved

horizon: 30 # Forecast horizon in days

feature_engineering:
  windows:
    - "7D"
    - "14D"
    - "30D"
    - "60D"
  diffs:
    days: [1, 2, 3, 4, 5, 6, 14, 30]
  lags:
    days: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]  # 0-lag is the current day, 1-lag is yesterday, etc.
    weeks: [3, 4]
    months: [2, 3, 4, 5, 6]
    years: [1]
  holidays:
    sigma: 1.3        # Standard deviation for the Gaussian function used in the holiday wave calculation. 
                      # Sigma is the 60% memory mark: the day before/after the holiday where the holiday 
                      # effect drops to roughly 60% of its maximum strength.
    extension_devs: 3 # Number of standard deviations to extend the holiday effect beyond the holiday date. 
                      # For example, if sigma=1.3 and extension_devs=3, the holiday effect will be considered 
                      # for days within 3*1.3 = 3.9 days before and after the holiday.
    country: DE       # Country code to extract holidays (Germany in this case) - we use the holidays package.
    language: en_US   # Language in which the holiday names will be returned - we use the holidays package.

cross_validation:
  n_outer_splits: 3
  n_inner_splits: 3

hypertuning:
  num_trials: 100            # Number of hyperparameter tuning trials to run. Each trial corresponds to a different set of hyperparameters being evaluated.
  timeout: 10800             # Timeout in seconds for hyperparameter tuning. If the tuning process exceeds this time, it will stop.
  seed: 42                   # Random seed for reproducibility of hyperparameter tuning results.
  monitor_periods: 100       # Number of periods to monitor during hyperparameter tuning.
  num_startup_trials: 10     # Number of trials to run before using the TPE sampler. These are used to explore the hyperparameter space randomly before the TPE algorithm starts to guide the search.
  num_jobs: -1               # Number of parallel jobs for hyperparameter tuning. -1 means using all available cores.
  early_stopping_rounds: 50  # Number of rounds with no improvement after which training will be stopped during hyperparameter tuning.
  num_boost_rounds: 10000    # Maximum number of boosting rounds for XGBoost. The actual number of rounds will be determined by early stopping.
  refit_val_fraction: 0.1    # Fraction of the training data to be used as a validation set for early stopping during hyperparameter tuning.

model_constants:
  tree_method: hist
  device: cpu
  objective: reg:squarederror
  eval_metric: rmse
  verbosity: 0

hyperparameters:  # XGBoost hyperparameters to be tuned using Optuna
  max_depth:
    method: suggest_int
    low: 3
    high: 10
    log: false
  learning_rate:
    method: suggest_float
    low: 1.0e-3
    high: 5.0e-2
    log: true
  subsample:
    method: suggest_float
    low: 0.6
    high: 1.0
    log: false
  colsample_bytree:
    method: suggest_float
    low: 0.6
    high: 1.0
    log: false
  min_child_weight:
    method: suggest_int
    low: 1
    high: 20
    log: false
  reg_alpha:
    method: suggest_float
    low: 1.0e-3
    high: 1.0
    log: true
  reg_lambda:
    method: suggest_float
    low: 1.0e-3
    high: 5.0
    log: true
  gamma:
    method: suggest_float
    low: 0.0
    high: 2.0
    log: false
